DOP_G4S/urls.py
from django.urls import path
from . import views


app_name = 'DOP_G4S'

urlpatterns = [

    # all_tranche_deux_heures_2
   # path('all_tranche_2', views.all_tranche_deux_heures_2, name='all_tranche_deux_heures_2'), 


######################## URLS CORRECTES ########################    
 # Accueil
    path('', views.accueil, name='accueil'), 

    # Alarme --- Choix de la carte à afficher
    path('choix_carte', views.alarme, name='alarme'),
    # Contact 
    path('contact', views.contact, name='contact'), 

    # Gestion de tous les declenchements par zone
    path('carte_all', views.carte_all, name='carte_all'), 
    path('carte_all_htmx/<str:pk>', views.carte_all_htmx, name='carte_all_htmx'), 

    # Gestion de tous les declenchements par le Type de client
    path('Type_client', views.type_client, name='type_client'), 
    path('Type_client_htmx/<str:pk>', views.Type_client_htmx, name='Type_client_htmx'), 

    # Gestion de tous les declenchements dont les interventions sont justifiées
    path('inter_justifie', views.inter_justifie, name='inter_justifie'), 
    path('inter_justifie_htmx/<str:pk>', views.inter_justifie_htmx, name='inter_justifie_htmx'), 

    # Gestion de tous les declenchements avec les tranches de deux heures
    path('all_tranche_deux_heures', views.all_tranche_deux_heures, name='all_tranche_deux_heures'), 
    path('all_tranche_deux_heures_htmx/<str:pk>', views.all_tranche_deux_heures_htmx, name='all_tranche_deux_heures_htmx'), 
     

######################## URLS CORRECTES ########################  

     ]

monsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('DOP_G4S.urls')),
]



templates/accueil.html
{% extends 'static/base.html' %}
   
    {% block title %}

        <title>Accueil</title>

    {% endblock %}


    {% block header %}

            {% include 'static/header.html' %}

    {% endblock %}


    {% block content %}

            <section  class="my-5" id="connection">
                <div class="container">
                    <div class="row gy-4 align-items-center">
                        <div class="col-12 col-md-12">
                            <h1 class="fw-bold text-md-center" id ="defile"><center>Cartographie des sites</center></h1>
                        </div>
                    </div>
                </div>
            </section>

            <section id="information" class="py-5 bg-light">
                <p class="lead mb-4 text-md-center" > 
                    Cet outil vous permet de cartographier l'ensemble des déclenchements alarme de nos sites à Abidjan dans le mois de Février 2024
                    <br> Pour visualiser la carte, veuillez cliquer sur le champ Alarme
                    <br> Pour vos remarques, critiques et suggestions, veuillez cliquer sur le champ contact<br>
                </p>
            </section>

            <br> 

    {% endblock %}

 
    

templates/alarme.html
{% extends 'static/base.html' %}
   
    {% block title %}

        <title>Carte </title>

    {% endblock %}

    {% block header %}

        {% include 'static/header.html' %}

    {% endblock %}

    {% block content %}
            <section  class="my-0" id="connection">
                <div class="container">
                    <div class="row gy-4 align-items-center">
                        <div class="col-12 col-md-12">
                            <h1 class="fw-bold text-md-center" id ="defile"><center>Cartographie des declenchements alarmes à Abidjan </center></h1>
                        </div>
                    </div>
                </div>
            </section>
             <marquee><i>Les données proviennent des déclenchements des sites alarmes de la ville d'Abidjan dans le mois de Février 2024</i></marquee>   
            <section id="information" class="py-5 bg-light">
                <div class="container">

                    <div class="row" >
                       <h5 class="text-center"> Veuillez cliquer sur l'un des boutons ci-dessous pour visualiser une carte </h5>
                    </div>
                    <br>
                    
                    <div class="row">
                        <div class="col-sm-6">
                          <div class="card">
                            <div class="card-body">
                              <h5 class="card-title">Tous les declenchements</h5>
                              <p class="card-text">La carte représente tous les déclenchements</p>
                              <a href="{% url 'DOP_G4S:carte_all' %}" target="_blank" class="btn btn-primary">Envoyer</a>
                            </div>
                          </div>
                        </div>
                        <div class="col-sm-6">
                          <div class="card">
                            <div class="card-body">
                              <h5 class="card-title">Tous les declenchements</h5>
                              <p class="card-text">La carte représente tous les déclenchements par tranche de deux heures</p>
                              <a href="{% url 'DOP_G4S:all_tranche_deux_heures' %}" target="_blank" class="btn btn-primary">Envoyer</a> 
                            </div> 
                          </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-6">
                          <div class="card">
                            <div class="card-body">
                              <h5 class="card-title">Intervention Justifiée</h5>
                              <p class="card-text">936 declenchements : 935 chez les bancaires et 01 non bancaire</p>
                              <a href="{% url 'DOP_G4S:inter_justifie' %}" target="_blank" class="btn btn-primary">Envoyer</a>
                            </div>
                          </div>
                        </div>
                        <div class="col-sm-6">
                          <div class="card">
                            <div class="card-body">
                              <h5 class="card-title">Type de client : sensible (DG, Ministre) et non sensible</h5>
                              <p class="card-text">63 déclenchements dont 6 chez les clients sensibles</p>
                              <a href="{% url 'DOP_G4S:type_client' %}" target="_blank" class="btn btn-primary">Envoyer</a>
                            </div>
                          </div>
                        </div>
                      </div>
            
    {% endblock %}

templates/carte_all.html
{% extends 'static/base.html' %}
   
    {% block title %}

        <title>Carte</title>

        <style>
          body{
          margin : 0; 
          padding : 0; 
          }
         
         html, body, main, #map { 
          height: 100%; 
          width: 100%; }
      </style>

    {% endblock %}

    {% block content %}
    <section id="information" class="my-1 bg-light">
      <div class="container">
          <div class="row">
            <div class="col-2">
              <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Cliquez ici
              </button>
            </div>
            <div class="col-10">
              <marquee>Cartographie des declenchements alarme par Zone au mois de Février 2024. Pour faire
                une selection, cliquez sur le bouton à gauche </marquee>  
            </div>  

          </div>  
          
  </section> 

            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Choix à faire</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    
                    <div class="zoneChoix" onclick="clique()">
                      <div class="row"> 
                        <div class="col"> 
                          <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault1" checked>
                            <label class="form-check-label" for="flexSwitchCheckDefault">Boston</label>
                          </div>

                          <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault2" checked>
                            <label class="form-check-label" for="flexSwitchCheckDefault">Detroit</label>
                          </div>

                        </div>
                        <div class="col"> 
                          <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault3" checked>
                            <label class="form-check-label" for="flexSwitchCheckDefault">Malibu</label>
                          </div>

                          <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault4" checked>
                            <label class="form-check-label" for="flexSwitchCheckDefault">Monaco</label>
                          </div>

                        </div>
                        <div class="col"> 
                          <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault5" checked>
                            <label class="form-check-label" for="flexSwitchCheckDefault">Orleans</label>
                          </div>

                          <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault6" checked>
                            <label class="form-check-label" for="flexSwitchCheckDefault">Sydney</label>
                          </div>

                        </div>

                      </div>
                  
                    </div>
                   
                  </div>
                  
                </div>
              </div>
            </div>
        <!-- Fenêtre modale-->

                  
 <!-- Affiche la carte ici -->
<div id="map" >{{map|safe}}</div>

<script >  
          function clique(){
           // input = "0 1 2";
            //  htmx.ajax('GET', `/exemple_htmx/${texte}`, {target:'#map', swap:'innerHTML'});

              choix = " "
              let listeInputRadio = document.querySelectorAll(".zoneChoix input");
              //console.log(listeInputRadio);
              for (let i = 0; i < listeInputRadio.length; i++) {
                if (listeInputRadio[i].checked === true) { 
                      //console.log(i)  ; 
                      choix = choix + i.toLocaleString();
                }}
                if (choix === " "){choix = "aucun";}  
                htmx.ajax('GET', `/carte_all_htmx/${choix}`, {target:'#map', swap:'innerHTML'});  
         
            } 
</script>

    {% endblock %}

templates/contact.html
{% extends 'static/base.html' %}
   
    {% block title %}

        <title>Contact</title>

    {% endblock %}


    {% block header %}

        {% include 'static/header.html' %}

    {% endblock %}


    {% block content %}

            <section  class="my-5" id="connection">
                <div class="container">
                    <div class="row gy-4 align-items-center">
                        <div class="col-12 col-md-12">
                            <h1 class="fw-bold text-md-center" id ="defile"><center>Contact</center></h1>
                        </div>
                    </div>
                </div>
            </section>

            <section id="information" class="py-5 bg-light">
                <p class="lead mb-4 text-md-center" > 
                    Pour toutes vos remarques, critiques et suggestions, veuillez-vous adresser à : 
                                
                </p>

                <p class="lead mb-4 text-md-center" > 
                   
                    <a href="#" type="button" class="btn btn-secondary">richard.kouassi@ci.g4s.com</a>

                </p>

            </section> 
            
    {% endblock %}

templates/declenchement_all.html

<section id="information" class="py-5 bg-light">
    <div class="container">
        <div class="row" text-align="center">
            Cartographie de tous les declenchements des sites alarme du mois de Février 2024
        </div>  
        <br>
        <div class="row">
            {{map|safe}}
        </div>   
    </div>    

</section> 

templates/inter_justifie.html
{% extends 'static/base.html' %}
   
 {% block title %}
        
                <title>Carte Intervention Justifiée</title>
        
                <style>
                  body{
                  margin : 0; 
                  padding : 0; 
                  }
                 
                 html, body, main, #map { 
                  height: 100%; 
                  width: 100%; }
              </style>
        
            {% endblock %}
        
            {% block content %}
            <section id="information" class="my-1 bg-light">
              <div class="container">
                  <div class="row">
                    <div class="col-2">
                      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                        Cliquez ici
                      </button>
                    </div>
                    <div class="col-10">
                      <marquee>Cartographie des declenchements des alarmes dont les interventions sont justifiées du mois de Février 2024. Pour faire
                        une selection, cliquez sur le bouton à gauche </marquee>  
                    </div>  
        
                  </div>  
                  
          </section> 
        
                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Choix à faire</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body"> 
                                <div class="zoneChoix" onclick="clique()">
                                    <div class="row"> 
                                        <div class="col"> 
                                            <div class="form-check form-switch">
                                                <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault1" checked>
                                                <label class="form-check-label" for="flexSwitchCheckDefault">Bancaire</label>
                                            </div>
                                        </div>
                                        <div class="col">     
                                            <div class="form-check form-switch">
                                                <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault2" checked>
                                                <label class="form-check-label" for="flexSwitchCheckDefault">Non Bancaire</label>
                                            </div>
                                        </div>    
        
                                    </div>
                                    
                                </div>
        
                                </div>
                            
                            </div>
                            
                            </div>
                            </div>
                            
                            </div>
                            
                    </div>
                <!-- Fenêtre modale-->
        
               
                          
                <!-- Affiche la carte ici -->
                <div id="map" >{{map|safe}}</div>
        
        <script >  
                  function clique(){
                   // input = "0 1 2";
                    //  htmx.ajax('GET', `/exemple_htmx/${texte}`, {target:'#map', swap:'innerHTML'});
        
                      choix = " "
                      let listeInputRadio = document.querySelectorAll(".zoneChoix input");
                      //console.log(listeInputRadio);
                      for (let i = 0; i < listeInputRadio.length; i++) {
                        if (listeInputRadio[i].checked === true) { 
                              //console.log(i)  ; 
                              choix = choix + i.toLocaleString();
                        }}
                        if (choix === " "){choix = "aucun";}  
                        htmx.ajax('GET', `inter_justifie_htmx/${choix}`, {target:'#map', swap:'innerHTML'});  
                 
                    } 
        </script>
        
            {% endblock %}
        

           


templates/tranche_deux_heures.html
{% extends 'static/base.html' %}
   
 {% block title %}
        
                <title>Carte declenchements par tranche de deux heures</title>
        
                <style>
                  body{
                  margin : 0; 
                  padding : 0; 
                  }
                 
                 html, body, main, #map { 
                  height: 100%; 
                  width: 100%; }
              </style>
        
            {% endblock %}
        
            {% block content %}
            <section id="information" class="my-1 bg-light">
              <div class="container">
                  <div class="row">
                    <div class="col-2">
                      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                        Cliquez ici
                      </button>
                    </div>
                    <div class="col-10">
                      <marquee>Cartographie de tous les declenchements alarme par tranche de deux heures au mois de Février 2024. Pour faire
                        une selection, cliquez sur le bouton à gauche </marquee>  
                    </div>  
        
                  </div>  
                  
          </section> 
        
                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Choix à faire</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body"> 
                                <div class="zoneChoix" onclick="clique()">
                                    <div class="row"> 
                                        <div class="col">
                                        <div class="form-check form-switch">
                                            <input class="form-check-input" type="checkbox" id="deselectionner" >
                                            <label class="form-check-label" for="flexSwitchCheckDefault">Cliquez ici pour tout deselectionner</label>
                                        </div>
                                        </div>
                                    </div> <br>
                                    <div class="row"> 
                                        <div class="col"> 
                                            <div class="form-check form-switch">
                                                <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault1" checked>
                                                <label class="form-check-label" for="flexSwitchCheckDefault">00H - 02H</label>
                                            </div>
                                        </div>
                                        <div class="col">     
                                            <div class="form-check form-switch">
                                                <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault2" checked>
                                                <label class="form-check-label" for="flexSwitchCheckDefault">02H - 04H</label>
                                            </div>
                                        </div> 
                                        
                                        <div class="col">     
                                            <div class="form-check form-switch">
                                                <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault2" checked>
                                                <label class="form-check-label" for="flexSwitchCheckDefault">04H - 06H</label>
                                            </div>
                                        </div> 
        
                                    </div>

                                    <div class="row"> 
                                        <div class="col"> 
                                            <div class="form-check form-switch">
                                                <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault1" checked>
                                                <label class="form-check-label" for="flexSwitchCheckDefault">06H - 08H</label>
                                            </div>
                                        </div>
                                        <div class="col">     
                                            <div class="form-check form-switch">
                                                <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault2" checked>
                                                <label class="form-check-label" for="flexSwitchCheckDefault">08H - 10H</label>
                                            </div>
                                        </div> 
                                        
                                        <div class="col">     
                                            <div class="form-check form-switch">
                                                <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault2" checked>
                                                <label class="form-check-label" for="flexSwitchCheckDefault">10H - 12H</label>
                                            </div>
                                        </div> 
        
                                    </div>

                                    <div class="row"> 
                                        <div class="col"> 
                                            <div class="form-check form-switch">
                                                <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault1" checked>
                                                <label class="form-check-label" for="flexSwitchCheckDefault">12H - 14H</label>
                                            </div>
                                        </div>
                                        <div class="col">     
                                            <div class="form-check form-switch">
                                                <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault2" checked>
                                                <label class="form-check-label" for="flexSwitchCheckDefault">14H - 16H</label>
                                            </div>
                                        </div> 
                                        
                                        <div class="col">     
                                            <div class="form-check form-switch">
                                                <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault2" checked>
                                                <label class="form-check-label" for="flexSwitchCheckDefault">16H - 18H</label>
                                            </div>
                                        </div> 
        
                                    </div>

                                    <div class="row"> 
                                        <div class="col"> 
                                            <div class="form-check form-switch">
                                                <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault1" checked>
                                                <label class="form-check-label" for="flexSwitchCheckDefault">18H - 20H</label>
                                            </div>
                                        </div>
                                        <div class="col">     
                                            <div class="form-check form-switch">
                                                <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault2" checked>
                                                <label class="form-check-label" for="flexSwitchCheckDefault">20H - 22H</label>
                                            </div>
                                        </div> 
                                        
                                        <div class="col">     
                                            <div class="form-check form-switch">
                                                <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault2" checked>
                                                <label class="form-check-label" for="flexSwitchCheckDefault">22H - 00H</label>
                                            </div>
                                        </div> 
        
                                    </div>
                                    
                                </div>
        
                                </div>
                            
                            </div>
                            
                            </div>
                            </div>
                            
                            </div>
                            
                    </div>
                <!-- Fenêtre modale-->
        
               
                          
                <!-- Affiche la carte ici -->
                <div id="map" >{{map|safe}}</div>
        
        <script >  
                  function clique(){
                   // input = "0 1 2";
                    //  htmx.ajax('GET', `/exemple_htmx/${texte}`, {target:'#map', swap:'innerHTML'});
        
                      choix = " "
                      let listeInputRadio = document.querySelectorAll(".zoneChoix input");
                      //console.log(listeInputRadio);
                      for (let i = 0; i < listeInputRadio.length; i++) {
                        if (listeInputRadio[i].checked === true) { 
                              //console.log(i)  ; 
                             if (i === 0) { 
                                for (let j = 1; j < listeInputRadio.length; j++) {listeInputRadio[j].checked = false}
                                break;
                             }
                             else {choix = choix + i.toLocaleString();}
                        }}
                        if (choix === " "){choix = "aucun";}  
                        htmx.ajax('GET', `all_tranche_deux_heures_htmx/${choix}`, {target:'#map', swap:'innerHTML'});  
                 
                    } 
        </script>
        
            {% endblock %}
        

           




templates/tranche_deux_heures_2.html

<section id="information" class="py-5 bg-light">
    <div class="container">
        <div class="row">
            Cartographie de tous les declenchements alarme par tranche de deux heures au mois de Février 2024
        </div>  
        <br>
        <div class="row">
            {{map|safe}}
        </div>   
    </div>    
</section> 
